desktopVersionFix
vitali-usik-work/training-landing-1 pull request #4
Opened 2016-12-11 19:16 UTC by IgorSinyak

JS and SCSS code corrctions

2016-12-12 07:43 UTC, vitali-usik requested changes

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
>    navList = $(NAV_LIST_ITEM_SELECTOR)
Missed `;`

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
> +    if ($(this).hasClass(CONTACT_ACTIVE_CLASS)){
Missed space before `{`

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
>      var cont = $(CONTACTS_SELECTOR);
Is it an array? If it - use contactsArray or similar. If not - use full word 'contact'.

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
> +    $(EMAIL_INPUT_ID).val("");
Please use quotes in one style. I advise `''`

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
>      $(this).data('placeholder', $(this).attr('placeholder'))
Missed ';'

2016-12-12 07:43 UTC, vitali-usik-work commented on js/script.js
> +
One blank line is extra

2016-12-12 07:43 UTC, vitali-usik-work commented on scss/main/main.scss
> +              &:before, &:after {
Move '&:after' to separate line

2016-12-12 07:43 UTC, vitali-usik-work commented on scss/main/main.scss
> +          transition: 0.2s;
Is this transition works correctly?

2016-12-12 08:05 UTC, IgorSinyak commented on scss/main/main.scss
> +          transition: 0.2s;
Yes, it works only for color

2016-12-15 12:15 UTC, vitali-usik approved these changes

2016-12-15 12:15 UTC, merged